### ISSUE TITLE
osx builds are failing 

### ISSUE THREAD

**Issue by rvalieris** [conda-forge/r-pbkrtest-feedstock#1]
from what I see in the logs, the problem is that the dependency r-nloptr is being installed from defaults instead of conda-forge channel.

but I don't understand why that is because [r-nloptr is available on conda-forge](https://anaconda.org/conda-forge/r-nloptr/files).

**Comment by bgruening** [comment]
This is normally because r-nloptr needs to be rerendered.

**Comment by rvalieris** [comment]
I just tried to rerender r-nloptr but it says:

    No changes made. This feedstock is up-to-date.

**Comment by bgruening** [comment]
I think I solved this already, but now the error is different :(

**Comment by cbrueffer** [comment]
Build is noarch these days, so the PR can be closed.
